In [2]:
import torch
import torchvision.datasets
import torchvision.transforms
import torch.utils.data.dataloader

In [3]:
train_data = torchvision.datasets.FashionMNIST(root = "./", train = True, download = True, transform = torchvision.transforms.ToTensor())
test_data = torchvision.datasets.FashionMNIST(root = "./", train = False, download = True, transform = torchvision.transforms.ToTensor())
# ToTensor()：將圖片轉成張量，並map至[0, 1]

In [28]:
image, label = train_data[0]
print(type(image))
print(image.size())
print(type(label))

<class 'torch.Tensor'>
torch.Size([1, 28, 28])
<class 'int'>


In [29]:
print(image)

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0039, 0.0000, 0.0000, 0.0510,
          0.2863, 0.0000, 0.0000, 0.0039, 0.0157, 0.0000,

In [4]:
train_loader = torch.utils.data.DataLoader(dataset = train_data, batch_size = 64, shuffle = True)

for batch in train_loader:
    print(type(batch))
    break

<class 'list'>


In [32]:
for images, labels in train_loader:
    print(images.shape)
    print(labels.shape)
    break

torch.Size([64, 1, 28, 28])
torch.Size([64])


In [33]:
class FashionModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(784, 128)
        self.relu = torch.nn.ReLU()
        self.output = torch.nn.Linear(128, 10)
        self.flatten = torch.nn.Flatten()
        self.mymodel = torch.nn.Sequential(
            self.flatten,
            self.linear,
            self.relu,
            self.output
        )

    def forward(self, x):
        return self.mymodel(x)



In [76]:
images, labels = next(iter(train_loader))
model = FashionModel()
pred = model(images)
print(images.shape)
print(pred.shape)
print(pred[0])
print(pred[0].sum())

torch.Size([64, 1, 28, 28])
torch.Size([64, 10])
tensor([ 0.0370,  0.0400, -0.1037,  0.0496, -0.1982,  0.2516,  0.0848, -0.1125,
        -0.3104, -0.0965], grad_fn=<SelectBackward0>)
tensor(-0.3584, grad_fn=<SumBackward0>)


In [73]:
prediction = torch.argmax(pred, dim = 1)
print(prediction.shape)
print(prediction[:10])
print(labels[:10])

torch.Size([64])
tensor([5, 5, 5, 5, 5, 5, 5, 6, 5, 5])
tensor([3, 5, 4, 5, 3, 4, 6, 6, 2, 3])


In [77]:
loss_fn = torch.nn.CrossEntropyLoss()
loss = loss_fn(pred, labels)
print(type(loss))
print(type(loss.item()))
print(loss)
print(loss.item())

<class 'torch.Tensor'>
<class 'float'>
tensor(2.3326, grad_fn=<NllLossBackward0>)
2.3325536251068115


In [78]:
optimizer = torch.optim.Adam(model.parameters(),
                             lr = 0.001)
optimizer.zero_grad()
print(model.linear.weight.grad)
loss.backward()
print(model.linear.weight.grad)
before = model.linear.weight.detach().clone()
optimizer.step()
after = model.linear.weight.detach().clone()
print(torch.equal(before, after))

None
tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -4.6018e-06,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  2.4957e-06,  7.4870e-06,  ...,  3.8184e-04,
          1.4974e-05,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  3.6327e-04,
          4.0945e-05,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  4.7401e-04,
          7.6453e-06,  0.0000e+00],
        [ 0.0000e+00, -7.0716e-07, -2.1215e-06,  ..., -3.6855e-04,
         -8.8393e-05,  0.0000e+00],
        [ 0.0000e+00, -3.1461e-06, -9.4383e-06,  ...,  7.0642e-04,
          6.8425e-07,  0.0000e+00]])
False


In [69]:
for name, param in model.named_parameters():
    print(name)

linear.weight
linear.bias
output.weight
output.bias


In [70]:
print(model.linear.weight.grad.abs().sum())

tensor(208.0693)


In [71]:
print(type(model.linear))

<class 'torch.nn.modules.linear.Linear'>


In [ ]:
device = "cuda"
model = FashionModel().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
loss_fn = torch.nn.CrossEntropyLoss()
for epoch in range(5):
    total_loss = 0
    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)
        pred = model(images)
        loss = loss_fn(pred, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    avg_loss  = total_loss / len(train_loader)
    print(f"Epoch {epoch + 1}: Loss = {avg_loss:.3f}")


Epoch 1: Loss = 0.548
Epoch 2: Loss = 0.402
Epoch 3: Loss = 0.364
Epoch 4: Loss = 0.335
Epoch 5: Loss = 0.316


In [ ]:
test_loader = torch.utils.data.DataLoader(dataset = test_data, batch_size = 64)

model.eval()
with torch.no_grad():
    correct = 0
    label_count = 0
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)
        pred = model(images)
        prediction = torch.argmax(pred, dim=1)
        correct += (prediction == labels).sum().item()
        label_count += len(labels)
    accuracy = correct / label_count
    print(accuracy)

0.868


In [5]:
class FashionConvModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv2d_1 = torch.nn.Conv2d(in_channels = 1, out_channels = 16, kernel_size = 3, padding = 1)
        self.relu = torch.nn.ReLU()
        self.maxpool2d = torch.nn.MaxPool2d(kernel_size = 2)
        self.conv2d_2 = torch.nn.Conv2d(in_channels = 16, out_channels = 32, kernel_size = 3, padding = 1)
        self.flatten = torch.nn.Flatten()
        self.linear = torch.nn.Linear(in_features = 1568, out_features = 128)
        self.output = torch.nn.Linear(in_features = 128, out_features = 10)
        self.model = torch.nn.Sequential(
            self.conv2d_1,
            self.relu,
            self.maxpool2d,
            self.conv2d_2,
            self.relu,
            self.maxpool2d,
            self.flatten,
            self.linear,
            self.relu,
            self.output
        )

    def forward(self, x):
        return self.model(x)

In [7]:
device = "cuda"
images, labels = next(iter(train_loader))
images = images.to(device)

model = FashionConvModel().to(device)
pred = model(images)

print(pred.shape)

torch.Size([64, 10])


In [ ]:
device = "cuda"
model = FashionConvModel().to(device)
optimizer = torch.optim.Adam(params = model.parameters(), lr = 0.001)
loss_fn = torch.nn.CrossEntropyLoss()
for epoch in range(5):
    total_loss = 0
    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)
        pred = model(images)
        loss = loss_fn(pred, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch + 1}: Average loss: {(total_loss / len(train_loader)):.3f}")




Epoch 1: Average loss: 0.515
Epoch 2: Average loss: 0.327
Epoch 3: Average loss: 0.282
Epoch 4: Average loss: 0.252
Epoch 5: Average loss: 0.229


In [12]:
test_loader = torch.utils.data.DataLoader(dataset = test_data, batch_size = 64)

model.eval()
with torch.no_grad():
    correct = 0
    cases = 0
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)
        pred = model(images)
        prediction = torch.argmax(pred, dim = 1)
        correct += (prediction == labels).sum()
        cases += len(labels)
    accuracy = correct / cases
    print(f"{accuracy:.3f}")



0.901


In [ ]:
torch.save(model.state_dict(), "fashion_cnn.pth")

In [16]:
new_model = FashionConvModel()
state_dict = torch.load("fashion_cnn.pth")
new_model.load_state_dict(state_dict)

C:\Users\hamuh\AppData\Local\Temp\ipykernel_19308\1340371344.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load("fashion_cnn.pth")


<All keys matched successfully>

In [20]:
confusion_matrix = torch.zeros(10, 10).to(device)
new_model.eval()
new_model = new_model.to(device)
num_classes = 10
with torch.no_grad():
    correct = 0
    cases = 0
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)
        pred = new_model(images)
        prediction = torch.argmax(pred, dim = 1)
        correct += (prediction == labels).sum()
        cases += len(labels)
        # 更新confusion matrix
        index = labels * num_classes + prediction
        confusion_matrix += torch.bincount(index, minlength = num_classes * num_classes).reshape(num_classes, num_classes)
    accuracy = correct / cases
    print(f"{accuracy:.3f}")

print(confusion_matrix.cpu().int())

0.901
tensor([[869,   0,  33,  15,   2,   1,  68,   0,  12,   0],
        [  2, 974,   2,  17,   1,   0,   3,   0,   1,   0],
        [ 13,   2, 902,   6,  32,   0,  42,   0,   3,   0],
        [ 20,   2,  17, 919,  22,   0,  19,   0,   1,   0],
        [  1,   1, 122,  25, 807,   0,  43,   0,   1,   0],
        [  0,   0,   0,   0,   0, 968,   0,  19,   1,  12],
        [146,   1,  90,  26,  67,   0, 658,   0,  12,   0],
        [  0,   0,   0,   0,   0,   2,   0, 952,   0,  46],
        [  3,   1,   3,   2,   1,   1,   0,   5, 984,   0],
        [  0,   0,   0,   0,   0,   3,   1,  22,   0, 974]], dtype=torch.int32)
